name: Lerna CI
on:
  push:
    branches:
      - master
      - next
      - 'test/*'
  pull_request:
    branches:
      - master
      - next
      - 'test/*'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Use Node.js ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [12, 14, 16]

    steps:
      - uses: actions/checkout@v3
      - name: bootstrap ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g lerna
      - run: npm install eslint-plugin-gb@latest -D
      - run: lerna bootstrap --hoist
      - run: npm test -- --verbose
